### ISSUE TITLE
Funzionalità statistiche richieste dalla commissione paritetica nel verbale del 12 giugno 2020

### ISSUE THREAD

**Issue by Wornairz** [UNICT-DMI/opis-manager-core#11]
1. Dato un CDS in input, dare in output tutte le schede opis di tutti gli insegnamenti del CDS di tutti gli anni accademici
2. Dato un insegnamento in input, dare in output tutte le schede opis di tutti gli anni accademici di quell'insegnamento

**Comment by LemuelPuglisi** [comment]
Essendo che: 
- per ogni anno accademico, viene salvato un cds / insegnamento differente dall'anno accademico precedente; 
- il progressivo identifica univocamente il record (quindi cambia per cds / insegnamento di anno in anno)
Ambo le API si baseranno sull'unict-id. 
A breve ne descriverò la struttura.

**Comment by LemuelPuglisi** [comment]
API richiesta nel punto 1: 
https://documenter.getpostman.com/view/8215228/SzzoZF9q?version=latest#bdf09381-d77f-4c18-9317-521ea9dee085

**Comment by LemuelPuglisi** [comment]
L'API relativa al punto 2 è documentata nel seguente link: 
https://documenter.getpostman.com/view/8215228/SzzoZF9q?version=latest#2c549944-fe7e-4ccb-a3da-68afd9c3ab47
Creo la PR e chiudo la issue.
