### ISSUE TITLE
Funzionalità amministratore richieste dalla commissione paritetica nel verbale del 12 giugno 2020

### ISSUE THREAD

**Issue by Wornairz** [UNICT-DMI/opis-manager-core#12]
1. Dare la possibilità ad un utente amministratore di modificare i pesi delle singole domande. Bisogna quindi salvare i pesi delle domande sul database.
1.1. Non è richiesto dalla commissione ma potrebbe essere utile dare la possibilità di modificare anche i pesi delle risposte
1.2. Impedire di avere gruppi di pesi di domande a somma maggiore di 1
2. Dare la possibilità ad un utente amministratore di modificare il valore di scostamento, uno per la numerosità di schede e uno per la media della valutazione. Bisogna quindi salvare questa coppia sul database.
2.1. Se non ho capito male questa coppia non è globale ma bisogna salvarne una per ogni CDS

**Comment by LemuelPuglisi** [comment]
Questo commit chiude il punto 1 e 1.2; tuttavia le API non sono ancora protette da autenticazione (ne parleremo in seguito).
