### ISSUE TITLE
Vincoli per insegnamento e schede_opis

### ISSUE THREAD

**Issue by Wornairz** [UNICT-DMI/opis-manager-core#18]
Attualmente, nel database, sono presenti dei vincoli di integrità solo per le tabelle dipartimento ed cds. Sarebbe opportuno aggiungerli anche ad insegnamento e schede_opis in modo da evitare record duplicati.

**Comment by LemuelPuglisi** [comment]
I valori che rendono l'insegnamento univoco sono i seguenti: 
* codice gomp
* anno accademico
* id modulo 
* canale 

Tuttavia, i campi *id_modulo* e *canale* possono assumere il valore NULL. Per la three-valued logic (3VL) il valore NULL, comparato con qualsiasi altro valore (NULL compreso), tornerà sempre falso. 
Supponiamo adesso di inserire il seguente corso: 

[codice gomp: X, anno accademico: Y, id modulo: NULL, canale: NULL]

La chiave dovrebbe garantire che esso non possa essere inserito più di una volta. Tuttavia, per il motivo citato precedentemente, la comparazione con i valori NULL ritornerà falso e il record verrà aggiunto (come non sperato).  

La soluzione a questa scomodo scenario potrebbe essere la seguente: rendere NOT NULL i campi problematici e inserire un valore standard "No". Che ne pensate?

**Comment by Wornairz** [comment]
Nelle statistiche del nucleo di valutazione:
- id_modulo, quando nessun modulo è presente, ha valore 0
- canale, quando l'insegnamento non ha un canale, ha valore "no"
